name: hybrid_browser
description: متصفح موحّد مع AI وترجمة وحفظ offline
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
