[Interface]
PrivateKey = QHom2VqtSyIMNXuokTgDrrtYZAi+JoHOd4RlwNyWR2g=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = lHVy08YWXIQkCAKSX6tw+SUvHKxwpU9Mujp115GlKAo=
Endpoint = 129.151.142.88:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25