[Interface]
PrivateKey = qBK3JMStbEFXEoYgOqd7qq14KPQRiqhlahVYS13jFVo=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = zB88hLft0bggvrdmMu4ccQbQwmlkbEnXwOyHHfhSdEg=
Endpoint = 129.151.142.88:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25