[Interface]
PrivateKey = YJOlQN6zgKZX4QTzwqxvQg7nWWJUvfvlspm0c14yw1g=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = MHfdwtkVSwSo0f9oWHfzc8cl658/f8npeh7q7dB09Sk=
Endpoint = 129.151.142.88:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25