[Interface]
Address = 10.66.66.1/24
ListenPort = 51820
PrivateKey = gHtfFLwkIiFl408aRQXDaxMNpPXZU3iTQekQdiH9VUw=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = GYSSvWi5T+/XnB8jMsw0FrOQ6IGPE6m52FWRIPZO0mc=
AllowedIPs = 10.66.66.2/32