[Interface]
Address = 10.66.66.1/24
ListenPort = 51820
PrivateKey = aIUiBkRyaHBvMz9aDxuumiRX3PoUtCz4jwxsBaS7bW8=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = WQWHvdpMVMD8w4Lw6cViz+GRmNzs43E7MKcyFW0sfUc=
AllowedIPs = 10.66.66.2/32