[Interface]
Address = 10.66.66.1/24
ListenPort = 51820
PrivateKey = 0IdRh4sl4TW1FWhq+ZB2S2oxUcQ4/9v02BnrnDhiU1M=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = OYDumgeBQRRxik9a5RRBX91zpzKV9evg3DHPkzovxHs=
AllowedIPs = 10.66.66.2/32